Add option to pass `contentSize` and `layoutMeasurement` when calling `scrollTo`
callstack/react-native-testing-library pull request #1543
Opened 2023-12-13 09:47 UTC by j-piasecki

### Summary

Adds option to specify `contentSize` and `layoutMeasurement` when calling `scrollTo`. This way it can also be used for components using `VirutalizedLists`, as those fields are used for updating the currently visible window.

Closes https://github.com/callstack/react-native-testing-library/issues/1540

### Test plan

I'm not sure how to test it properly, as entire `userEvent` API seems to be lacking tests at the moment.

2023-12-15 12:54 UTC, mdjastrzebski commented on src/user-event/scroll/scroll-to.ts
> +  emitContentSizeChangeEvent(element, options);
The sequencing of event matches our experiments with RN runtime:
https://github.com/callstack/react-native-testing-library/wiki/ScrollView-Events

2023-12-15 12:57 UTC, mdjastrzebski requested changes
The implementation looks good! Pls add some tests to verify it is working correctly on `FlatList`.

2023-12-15 15:07 UTC, j-piasecki commented on src/user-event/scroll/scroll-to.ts
> +  fireEvent(
`dispatchEvent` has a different signature than `fireEvent`. It expects `event` to be its last argument and passes that directly to the handler, while `fireEvent` accepts variadic arguments and spreads them when passing to the handler.

`contentSizeChange` handler expects `width` and `height` as separate arguments: https://github.com/facebook/react-native/blob/d45a01d6d15530e356065704adb869b1cbbb2576/packages/virtualized-lists/Lists/VirtualizedList.js#L1574

Should I also change the signature of `dispatchEvent` to accept variadic arguments, or is `fireEvent` fine in that case?

2023-12-15 15:47 UTC, mdjastrzebski commented on src/user-event/scroll/scroll-to.ts
> +  fireEvent(
Fair point, I'll add some dispatch function for such cases.

2023-12-15 17:30 UTC, mdjastrzebski approved these changes
I've done some tweaks. Ready for merge!

2023-12-15 17:32 UTC, merged

2023-12-18 15:34 UTC, mdjastrzebski commented
🎉 This PR has been release in RNTL [v12.4.2](https://github.com/callstack/react-native-testing-library/releases/tag/v12.4.2)!